spring:
  application:
    name: demo

  # Thymeleaf setting
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    spring:
      thymeleaf:
        suffix: .html

  # PostgreSQL setting
  datasource:
    url: your url
    driver-class-name: org.postgresql.Driver
    username: your username
    password: your password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # 起動時にEntityに対応するテーブルがなければ作成する
    hibernate:
      ddl-auto: update
    show-sql: true

# GoogleMap Api Key
api:
  key: your api key token

default:
  tokyo-lat: 35.68168615415703F
  tokyo-long: 139.76705199614096F
