INSERT INTO BULKY_GARBAGE_FACILITIES (LATITUDE, LONGITUDE, PREFECTURE, FACILITY_NAME) VALUES (33.5335, 130.4697, '福岡県', 'クリーン・エネ・パーク南部');
INSERT INTO BULKY_GARBAGE_FACILITIES (LATITUDE, LONGITUDE, PREFECTURE, FACILITY_NAME) VALUES (33.6342, 130.4823, '福岡県', '東部工場（福岡市）');
INSERT INTO BULKY_GARBAGE_FACILITIES (LATITUDE, LONGITUDE, PREFECTURE, FACILITY_NAME) VALUES (33.5678, 130.3217, '福岡県', '西部工場（福岡市）');
INSERT INTO BULKY_GARBAGE_FACILITIES (LATITUDE, LONGITUDE, PREFECTURE, FACILITY_NAME) VALUES (33.7256, 130.4772, '福岡県', 'エコロの森 古賀清掃工場');
INSERT INTO BULKY_GARBAGE_FACILITIES (LATITUDE, LONGITUDE, PREFECTURE, FACILITY_NAME) VALUES (33.8105, 130.5478, '福岡県', 'Ecoパーク宗像 宗像清掃工場');
