CREATE TABLE IF NOT EXISTS BULKY_GARBAGE_FACILITIES (
    LATITUDE INT NOT NULL,
    LONGITUDE INT NOT NULL,
    PREFECTURE INT NOT NULL,
    FACILITY_NAME CHAR(255) NOT NULL PRIMARY KEY,
    PRIMARY KEY (LATITUDE, LONGITUDE)
);
