CREATE TABLE IF NOT EXISTS BULKY_GARBAGE_FACILITIES (
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    PREFECTURE_NO INT NOT NULL,
    FACILITY_NAME CHAR(255) NOT NULL,
    PRIMARY KEY (LATITUDE, LONGITUDE),
    FOREIGN KEY (PREFECTURE_NO) REFERENCES PREFECTURES(PREFECTURE_NO)
);

CREATE TABLE PREFECTURES (
    NUMBER INT NOT NULL,
    PREFECTURE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (NUMBER)
);

